name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "09 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      - name: Upload animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
